BEGIN;

DROP TABLE IF EXISTS "Contacts" CASCADE;
DROP TABLE IF EXISTS "Departments" CASCADE;
DROP TABLE IF EXISTS "Languages" CASCADE;
DROP TABLE IF EXISTS "Organizations" CASCADE;
DROP TABLE IF EXISTS "Positions" CASCADE;
ALTER TABLE "surveys"
    DROP COLUMN IF EXISTS createdby;

COMMIT;
